---
title: "MIS637 Project"
author: "Ling Ao"
date: "4/23/2020"
output: pdf_document
---
```{r}
library('quantmod')
```

## 1 Read the name of stocks
```{r}
SP500 <- read.csv('S&P 500 data.csv')
SP500 <- na.omit(SP500[,1:4])
SP500 <- SP500[-c(91,241,269,363,449), ]
colnames(SP500) <- c('Symbol', 'Security', 'Industry', 'Subindustry')
Stock_names <- unique(as.character(SP500[,1]))  ### no repeat names

head(SP500)
```

## 2 Establish the data of current 2 months (frequent: weekly)
```{r}
Project.data <- vector()
for (i in 1:length(Stock_names)){
  stock_vector = t(weeklyReturn(getSymbols(Stock_names[i], from = '2020-2-15', to = '2020-05-04', auto.assign = F)))
  if (length(stock_vector) == 11){
    row.names(stock_vector) = Stock_names[i]
    Project.data = rbind(Project.data, stock_vector)
  }
}
Project.data <- data.frame(cbind(row.names(Project.data),Project.data))
row.names(Project.data) <- c(1:nrow(Project.data))
colnames(Project.data)[1] <- "Symbol"
Project.data <- Project.data[ ,-2]
```

## 3. Clustering
```{r}
clustering_result <- kmeans(Project.data[2:11], 3, iter.max = 10)
clustering_result
centers <- clustering_result$centers
```

### Plot the performance of centers:
```{r}
par(mfcol=c(1,3))
for (i in 1:3){
  plot(centers[i,], type = 'l',ylim = c(-0.4,0.4))
}
```

```{r}
SP500$Groups <- clustering_result$cluster

summary(SP500[SP500$Groups == "1", 3])
summary(SP500$Industry)
summary(SP500[SP500$Groups == "1", 3])/summary(SP500$Industry)
```

```{r}
sort(summary(SP500[SP500$Groups == "1", 3])/summary(SP500$Industry))
```





```{r}
sort(summary(SP500[SP500$Groups == "2", 3])/summary(SP500$Industry))
```

